Read /etc/gitorious.conf, adding Resque wrapper
/usr/libexec/gitoriousd/resque has a wrapper that:
- starts off daemonized
- forks a Resque worker and retains its pid
- kills and waits on Resque when receiving QUIT
- restarts Resque when receiving HUP

diff --git a/usr/sbin/gitoriousd b/usr/sbin/gitoriousd
--- a/usr/sbin/gitoriousd
+++ b/usr/sbin/gitoriousd
@@ -1,6 +1,20 @@
 #!/bin/sh
 progname="gitoriousd"
+# Dynamically find prefix
 prefix="/tmp/gitoriousd"
+# Read /etc/gitorious.conf, expose env vars
+current_dir=$(dirname $0)
+gitorious_conf=$current_dir/../../etc/gitorious.conf
+
+# Look for $PREFIX/gitorious.conf, source if present
+if [ -f $gitorious_conf ]; then
+    . $gitorious_conf
+    export GITORIOUS_HOME
+else
+    echo "gitorious.conf not found, exiting"
+    exit 1
+fi
+
 start(){
     for app in $(find "$prefix/usr/libexec/$progname" -type f -executable)
     do
